version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u sbpraonalla -p $DOCKER_HUB_TOKEN
      - echo "Customer Name: ${CUSTOMER_NAME}"
      - echo "ECR Repository Name: ${ECR_REPO_NAME}"
      - echo Checking if ECR repository exists.

  build:
    commands:
      - echo Building the Docker image...
      - docker build --no-cache -t ${CUSTOMER_NAME} .

  post_build:
    commands:
      - echo Tagging the Docker image...
      - export IMAGE_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${TAG_NAME}"
      - docker tag ${CUSTOMER_NAME}:latest ${IMAGE_URL}
      - echo Pushing the Docker image to ECR...
      - docker push ${IMAGE_URL}
      - echo "Image pushed successfully: ${IMAGE_URL}"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
